version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DBNAME=${MYSQL_DATABASE}
        - DBHOST=${HOST}
        - DBUSER=${MYSQL_USER}
        - DBPASS=${MYSQL_PASSWORD}
        - ROOT=${ROOT}
    container_name: php
    depends_on:
      - db
    image: php:8.2-apache
    environment:
      DBNAME: ${MYSQL_DATABASE}
      DBHOST: ${HOST}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      ROOT: ${ROOT}
    ports:
      - 80:80
    networks:
      - camagru
  db:
    container_name: mysql8
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - camagru
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
    networks:
      - camagru
networks:
  camagru:
    driver: bridge
