version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      args:
        - DBNAME=${MYSQL_DATABASE}
        - DBHOST=${HOST}
        - DBUSER=${MYSQL_USER}
        - DBPASS=${MYSQL_PASSWORD}
        - DBPORT=${MYSQL_DBPORT}
        - ROOT=${ROOT}
    container_name: php
    depends_on:
      - db
    image: php:8.2-apache
    environment:
      DBNAME: ${MYSQL_DATABASE}
      DBHOST: ${HOST}
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      DBPORT: ${MYSQL_DBPORT}
      ROOT: ${ROOT}
    ports:
      - 1025:80
    networks:
      - camagru
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3306
    networks:
      - camagru
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PMA_PORT: 3307
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
    networks:
      - camagru
networks:
  camagru:
    driver: bridge
